# Generated by Django 2.1 on 2018-09-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='text',
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='DEFAULT VALUE', max_length=10),
        ),
    ]
